import * as api from '@opentelemetry/api';
import axios from 'axios';
import { NextResponse } from 'next/server';

import { Logger } from '../../../utils/logUtil/logger';
import { createSpanByName } from '../../../utils/traceUtil/tracerUtility';

export async function GET() {
    try {
        const ret = createSpanByName('Main-Span', true, api.context.active());
        const response = await axios.get('http://localhost:3000/api/emp', { headers: ret?.carrier });
        const data = await response.data;
        return NextResponse.json({ data: { data } });
    } catch (error: unknown) {
        if (error instanceof Error) {
            const message = JSON.stringify({
                stackTrace: error.stack,
                errorMessage: error.message,
                additionalParameters: {
                    'Additional Information ': 'This is the error generated by traceUtility',
                },
            });
            Logger.logError(message);
        }
    }
}
